'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageSquare,Send,Loader2,X,PlusCircle} from 'lucide-react';
import type {Board,Method,Proposal} from '@/lib/board';
import {readBoard} from '@/lib/board';
type Message={role:'user'|'assistant';text:string;proposal?:Proposal;applied?:boolean};
export default function BoardChat({board,method,onApply,onClose}:{board:Board;method:Method;onApply:(p:Proposal)=>void;onClose:()=>void}){
const [messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const abort=useRef<AbortController|null>(null);const end=useRef<HTMLDivElement>(null);
useEffect(()=>()=>abort.current?.abort(),[]);useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[messages,busy]);
async function send(text=input){if(!text.trim()||busy)return;setInput('');setError('');const conversation=[...messages,{role:'user' as const,text:text.trim()}];setMessages(conversation);setBusy(true);abort.current=new AbortController();try{const r=await fetch('/api/board-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method,board:readBoard(board,method),messages:conversation.slice(-12).map(m=>({role:m.role,text:m.text}))}),signal:abort.current.signal});const response=await r.json();if(!r.ok)throw new Error(response.error||'The assistant could not respond.');setMessages(ms=>[...ms,{role:'assistant',text:response.message,proposal:response.nodes?.length||response.edges?.length?response:undefined}]);}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}finally{setBusy(false)}}
function apply(p:Proposal,index:number){try{onApply(p);setMessages(ms=>ms.map((m,i)=>i===index?{...m,applied:true}:m));setError('')}catch(e){setError((e as Error).message)}}
return <aside className="board-chat"><header><MessageSquare size={19}/><strong>Board assistant</strong><button aria-label="Close chat" onClick={onClose}><X size={17}/></button></header><div className="chat-scope">{method}<small>Gemini reads the current board when you send a message.</small></div><div className="chat-messages" aria-live="polite">{!messages.length&&<div className="chat-welcome"><h3>Make sense of the board</h3><p>Ask about its content or create new editable elements.</p>{['What do you see on this board?','What is missing from this analysis?','Create three useful additions to this board.'].map(t=><button key={t} onClick={()=>send(t)}>{t}</button>)}</div>}{messages.map((m,i)=><div className={`chat-message ${m.role}`} key={i}><small>{m.role==='user'?'You':'Gemini'}</small><p>{m.proposal?"Review these proposed additions, then choose Add to board to apply them.":m.text}</p>{m.proposal&&<div className="proposal"><strong>Proposal · {m.proposal.nodes.length} elements · {m.proposal.edges.length} connections</strong><ul>{m.proposal.nodes.slice(0,6).map(n=><li key={n.id}>{n.kind}: {n.label}</li>)}</ul><button className="btn" disabled={m.applied} onClick={()=>apply(m.proposal!,i)}><PlusCircle size={15}/>{m.applied?'Added to board':'Add to board'}</button></div>}</div>)}{busy&&<div className="chat-thinking"><Loader2 size={16} className="animate-spin"/>Reading the board… <button onClick={()=>abort.current?.abort()}>Cancel</button></div>}{error&&<div role="alert" className="chat-error">{error}<button onClick={()=>{const last=messages.filter(m=>m.role==='user').at(-1);if(last)send(last.text)}}>Retry</button></div>}<div ref={end}/></div><form className="chat-compose" onSubmit={e=>{e.preventDefault();send()}}><textarea aria-label="Message the board assistant" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask or describe what to create…" maxLength={4000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><button type="submit" aria-label="Send message" disabled={busy||!input.trim()}><Send size={17}/></button></form><p className="chat-disclosure">Messages and current board content are sent to Google Gemini. Proposed additions need your click and can be undone.</p></aside>}
