'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,Send,MessageSquarePlus,Loader2,X,PlusCircle} from 'lucide-react';
import {readBoard,type Method,type Proposal} from '@/lib/board';
import {type CaseData,type StepId,fieldLabels,stepTitles,methodCatalog} from '@/lib/case-data';
import type {Snapshot} from '@/lib/editor-types';
type ChatMessage={role:'user'|'assistant';text:string;proposal?:Proposal;targetId?:string;applied?:boolean};
export type ChatFocus={id:string;method:string;type:string;title:string;snapshot:Snapshot};
export default function CaseChat({guest=false,data,step,focus,onApply,onHide}:{guest?:boolean;data:CaseData;step:StepId;focus?:ChatFocus;onApply:(p:Proposal)=>void;onHide:()=>void}){
 const [messages,setMessages]=useState<ChatMessage[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const abort=useRef<AbortController|null>(null),end=useRef<HTMLDivElement>(null);const focused=useRef(focus);focused.current=focus;
 useEffect(()=>()=>abort.current?.abort(),[]);useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[messages,busy]);
 async function send(text=input){if(guest||busy||!text.trim())return;const conversation=[...messages,{role:'user' as const,text:text.trim()}];setMessages(conversation);setInput('');setError('');setBusy(true);abort.current=new AbortController();const sentFocus=focus;
 try{const history=conversation.slice(-12).map(m=>({role:m.role,text:m.text}));const isBoard=focus?.type==='flow'&&focus.snapshot.data?.nodes;const context=JSON.stringify({currentStep:`${step}. ${stepTitles[step]}`,fields:data.steps[step].fields.map((text,i)=>({question:fieldLabels[step][i],text})),savedMethods:data.items.filter(i=>i.step===step).map(i=>({title:i.title,type:i.kind,text:i.text||'',attachment:i.kind==='file'?i.title:undefined})),activeDocument:focus?.type==='docs'?{title:focus.title,text:focus.snapshot.text}:undefined});
 const r=await fetch(isBoard?'/api/board-chat':'/api/case-chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:abort.current.signal,body:JSON.stringify(isBoard?{method:focus!.method,board:readBoard(focus!.snapshot.data,focus!.method as Method),messages:history}:{context,messages:history})});const result=await r.json();if(!r.ok)throw Error(result.error||'The assistant could not respond.');const proposal=result.nodes?.length||result.edges?.length?result:undefined;setMessages(ms=>[...ms,{role:'assistant',text:proposal?'Review these proposed additions, then add them to your method.':result.message,proposal,targetId:sentFocus?.id}]);
 }catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}finally{setBusy(false)}}
 function apply(m:ChatMessage,index:number){if(focused.current?.id!==m.targetId){setError('Open the method this proposal was created for to apply it.');return}try{onApply(m.proposal!);setMessages(ms=>ms.map((v,i)=>i===index?{...v,applied:true}:v));setError('')}catch(e){setError((e as Error).message)}}
 return <aside className="case-assistant"><header><MessageSquarePlus size={24}/><h2>Assistant</h2><button className="mobile-chat-close icon-button" aria-label="Hide assistant" onClick={onHide}><X size={19}/></button></header>{focus&&<div className="assistant-focus"><span>Working on</span><strong>{focus.title}</strong><small>{focus.type==='flow'?'Can read this board and propose additions':'Can read this document and suggest content'}</small></div>}<div className="case-chat-messages" aria-live="polite">{!messages.length&&<div className="assistant-empty"><Sparkles size={24}/><p>{focus?'Ask about this method or what to add.':'Ask anything about this problem case.'}</p></div>}{messages.map((m,i)=><div className={`case-message ${m.role}`} key={i}><small>{m.role==='user'?'You':'Assistant'}</small><p>{m.text}</p>{m.proposal&&<div className="proposal"><strong>{m.proposal.nodes.length} elements · {m.proposal.edges.length} connections</strong><ul>{m.proposal.nodes.slice(0,5).map(n=><li key={n.id}>{n.label}</li>)}</ul><button className="case-button" disabled={m.applied||focus?.id!==m.targetId} onClick={()=>apply(m,i)}><PlusCircle size={15}/>{m.applied?'Added to draft':'Add to board'}</button>{!m.applied&&focus?.id!==m.targetId&&<small>Reopen the original method to apply.</small>}</div>}</div>)}{busy&&<div className="chat-thinking"><Loader2 size={16} className="animate-spin"/>Thinking… <button onClick={()=>abort.current?.abort()}>Cancel</button></div>}{error&&<div className="case-error" role="alert">{error}<button onClick={()=>send(messages.filter(m=>m.role==='user').at(-1)?.text||'Try again')}>Retry</button></div>}<div ref={end}/></div><form className="case-chat-form" onSubmit={e=>{e.preventDefault();send()}}><textarea aria-label="Message the assistant" disabled={guest} placeholder={focus?'Ask about this method…':'Ask a question about this problem…'} value={input} maxLength={4000} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><button aria-label="Send message" disabled={guest||busy||!input.trim()}><Send size={18}/></button></form>{guest&&<p className="assistant-privacy"><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in to use the AI assistant.</a> Methods work without signing in.</p>}<p className="assistant-disclaimer">AI generated responses. Verify results.</p><p className="assistant-privacy">Messages and current step or method content are sent to Google Gemini when you send.</p></aside>
}
