'use client';
import {useState,useMemo,useRef,useEffect} from 'react';
import {Excalidraw,MainMenu,DefaultSidebar,convertToExcalidrawElements,exportToBlob} from '@excalidraw/excalidraw';
import '@excalidraw/excalidraw/index.css';
import {EditorProps,readSaved,saveLocal} from '@/lib/editor-types';
import {Plus,ImageDown} from 'lucide-react';
function template(method:string){const names=method==='Timeline'?['02 Aug · 08:00\nFormat change introduced','05 Aug · 14:30\nFirst extended changeover','08 Aug · 09:15\nQA clearance delay recorded']:method==='Process Map'?['Stop & clean line','Change format parts','QA clearance','Restart production']:['QA clearance','Equipment set-up','Waiting for release','Cartoner adjustment'];const shapes:any[]=[{type:'text',x:90,y:65,text:method,fontSize:28,fontFamily:2}];names.forEach((text,i)=>{shapes.push({type:'rectangle',id:`card-${i}`,x:90+(i%3)*280,y:165+Math.floor(i/3)*210,width:230,height:125,backgroundColor:method==='Affinity Diagram'?'#fff3bf':'#e3f4f1',strokeColor:'#187c77',roughness:0,roundness:{type:3},label:{text,fontSize:18,fontFamily:2}});if(i<names.length-1&&method!=='Affinity Diagram')shapes.push({type:'arrow',x:330+(i%3)*280,y:227+Math.floor(i/3)*210,width:35,height:0,points:[[0,0],[35,0]],roughness:0,strokeColor:'#187c77'})});return convertToExcalidrawElements(shapes)}
export default function ExBoard({method,onSnapshot}:EditorProps){const [api,setApi]=useState<any>(null);const [saved,setSaved]=useState(true);const last=useRef('');const key=`studio-excalidraw-${method}`;const initial=useMemo(()=>{const s=readSaved(key);return s?{elements:s.elements,files:s.files,appState:{viewBackgroundColor:'#ffffff'}}:{elements:template(method),appState:{viewBackgroundColor:'#ffffff',scrollX:0,scrollY:0}}},[key,method]);
useEffect(()=>{if(api){const timer=setTimeout(()=>api.scrollToContent(api.getSceneElements(),{fitToContent:true,maxZoom:1}),100);return ()=>clearTimeout(timer)}},[api]);
function add(kind:string){if(!api)return;const state=api.getAppState();const x=-state.scrollX+180,y=-state.scrollY+280;const els=convertToExcalidrawElements([{type:'rectangle',x,y,width:230,height:125,backgroundColor:kind==='Note'?'#fff3bf':'#e3f4f1',strokeColor:'#187c77',roughness:0,label:{text:kind==='Event'?'Date / time\nNew event':`New ${kind.toLowerCase()}`,fontSize:18,fontFamily:2}}]);api.updateScene({elements:[...api.getSceneElements(),...els]})}
async function png(){try{const blob=await exportToBlob({elements:api.getSceneElements(),appState:{...api.getAppState(),exportWithDarkMode:false},files:api.getFiles(),mimeType:'image/png'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${method}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{window.alert('Could not export this board. Please export JSON to keep your work.')}}
return <div className="board-stack"><div className="palette"><span>Suggested elements</span>{(method==='Timeline'?['Event','Note']:method==='Process Map'?['Process step','Decision','Note']:['Group','Note']).map(k=><button className="chip" key={k} onClick={()=>add(k)} disabled={!api}><Plus size={14}/>{k}</button>)}<button className="chip" onClick={png} disabled={!api}><ImageDown size={14}/>Export PNG</button><small>{saved?'Saved locally':'Local storage full — export your work'}</small></div><div className="ex-canvas"><Excalidraw excalidrawAPI={setApi} initialData={initial} theme="light" onChange={(elements,appState,files)=>{const data={elements,files};const serialized=JSON.stringify(data);if(serialized===last.current)return;last.current=serialized;setSaved(saveLocal(key,data));onSnapshot({text:elements.filter((e:any)=>!e.isDeleted&&e.type==='text').map((e:any)=>e.text).join('\n\n'),data})}} UIOptions={{canvasActions:{loadScene:false,saveToActiveFile:false,export:false,saveAsImage:false}}}><MainMenu><MainMenu.DefaultItems.ChangeCanvasBackground /></MainMenu><DefaultSidebar.Trigger style={{display:'none'}} /></Excalidraw></div></div>}
