'use client';
import {createContext,useContext} from 'react';
import {Handle,Position,NodeResizer} from '@xyflow/react';
import {Plus} from 'lucide-react';
export const BoardActions=createContext<{update:(id:string,key:string,value:string)=>void;child:(id:string)=>void;checkpoint:()=>void}>({update:()=>{},child:()=>{},checkpoint:()=>{}});
function Ports({data}:any){const d=data.direction;const vertical=d==='TB'||d==='BT';const input=vertical?(d==='TB'?Position.Top:Position.Bottom):Position.Left;const output=vertical?(d==='TB'?Position.Bottom:Position.Top):Position.Right;
if(d==='free')return null;return <><Handle id="in" type="target" position={input}/><Handle id="out" type="source" position={output}/>{data.method==='Events & Causal Factors Chart'&&d==='LR'&&<Handle id="top-out" type="source" position={Position.Top}/>}{data.method==='Process Map'&&<><Handle id="branch" type="source" position={Position.Bottom}/><Handle id="branch-in" type="target" position={Position.Bottom} style={{left:'65%'}}/><Handle id="top" type="target" position={Position.Top}/><Handle id="top-out" type="source" position={Position.Top} style={{left:'65%'}}/></>}{data.direction==='TB'&&<Handle id="right" type="source" position={Position.Right}/>}</>}
function Geometry({kind,method,status}:any){let shape;const shared={vectorEffect:'non-scaling-stroke' as const};if(['Causal factor','Root cause'].includes(kind))shape=<><polygon points="24,3 216,3 238,80 216,157 24,157 2,80" {...shared}/>{kind==='Root cause'&&<polygon points="29,10 211,10 230,80 211,150 29,150 10,80" fill="none" {...shared}/>}</>;
else if(['Problem','Top event','Decision','Diamond'].includes(kind))shape=<polygon points="120,2 238,80 120,158 2,80" {...shared}/>;
else if(['Condition','Basic event','Ellipse'].includes(kind))shape=<ellipse cx="120" cy="80" rx="118" ry="78" {...shared}/>;
else if(kind==='AND gate')shape=<path d="M35 157 L35 78 A85 75 0 0 1 205 78 L205 157 Z" {...shared}/>;
else if(kind==='OR gate')shape=<path d="M35 150 Q65 80 120 8 Q175 80 205 150 Q120 122 35 150 Z" {...shared}/>;
else if((method==='Timeline'&&kind==='Event')||kind==='Process step')shape=<polygon points="2,2 213,2 238,80 213,158 2,158 24,80" {...shared}/>;
else shape=<rect x="2" y="2" width="236" height="156" rx={kind==='Note'?2:8} {...shared}/>;
return <svg className={`method-geometry ${status==='Assumption'?'assumed':''}`} viewBox="0 0 240 160" preserveAspectRatio="none" aria-hidden="true">{shape}</svg>}
export function MethodNode({id,data,selected}:any){const a=useContext(BoardActions);const kind=data.kind;const diamond=['Problem','Top event','Decision','Diamond'].includes(kind);const shaped=['Causal factor','Root cause','Condition','Basic event','Ellipse'].includes(kind);const text=kind==='Text';const gate=kind.endsWith('gate');return <div className={`method-node ${diamond?'node-diamond':''} ${shaped?'node-shaped':''} ${gate?'node-gate':''} ${kind==='Note'?'node-note':''} ${kind==='Event'?'node-event':''} ${text?'node-text':''} ${data.highlight?'node-highlight':''} ${selected?'selected':''}`}><NodeResizer onResizeStart={a.checkpoint} isVisible={selected} minWidth={gate?80:180} minHeight={gate?80:100}/>{!text&&<Geometry {...data}/>}<div className="method-node-body"><div className="node-drag-label">{kind}</div>{kind==='Event'&&data.method==='Timeline'&&<input className="nodrag node-date" aria-label="Event date" placeholder="Date / time" value={data.date||''} onChange={e=>a.update(id,'date',e.target.value)}/>}<textarea className="nodrag nowheel" aria-label={`${kind} text`} placeholder={text?'Write here…':'Add details…'} value={data.label||''} onChange={e=>a.update(id,'label',e.target.value)}/>{data.status&&<button className={`node-status nodrag ${data.status==='Confirmed'?'confirmed':''}`} title="Toggle assumption / confirmed" onClick={()=>a.update(id,'status',data.status==='Assumption'?'Confirmed':'Assumption')}>{data.status}</button>}</div><Ports data={data}/>{!gate&&['LR','TB'].includes(data.direction)&&!text&&<button className={`add-connected nodrag ${data.direction==='TB'?'below':''}`} title={data.direction==='TB'?'Add child':'Add next element'} aria-label={data.direction==='TB'?'Add child':'Add next element'} onClick={()=>a.child(id)}><Plus size={13}/></button>}</div>}
export function FrameNode({id,data,selected}:any){const a=useContext(BoardActions);return <div className={`method-frame tone-${data.tone||'blue'} ${data.kind==='Lane'?'lane-frame':''}`}><NodeResizer onResizeStart={a.checkpoint} isVisible={selected&&data.kind!=='Lane'} minWidth={300} minHeight={250}/>{data.kind==='Lane'?<strong>{data.label}</strong>:<input className="nodrag" aria-label="Group title" value={data.label} onChange={e=>a.update(id,'label',e.target.value)}/>}<span className="frame-grip">{data.kind==='Lane'?'': 'Drag border to move group'}</span></div>}
export function MatrixNode(){return <div className="method-matrix"><div className="matrix-title">Impact / ease of implementation</div><span className="impact-axis">Impact ↑</span><div className="quadrant-grid"><div><strong>Evaluate further</strong><small>High impact · Difficult</small></div><div><strong>Highest priority</strong><small>High impact · Easy</small></div><div><strong>Lowest priority</strong><small>Low impact · Difficult</small></div><div><strong>Evaluate further</strong><small>Low impact · Easy</small></div></div><div className="ease-axis"><span>Difficult</span>Ease of implementation →<span>Easy</span></div></div>}
export function FreehandNode({data,selected}:any){const a=useContext(BoardActions);return <div className={`freehand-node ${selected?'is-selected':''}`}><NodeResizer onResizeStart={a.checkpoint} isVisible={selected} minWidth={20} minHeight={20}/><svg viewBox={`0 0 ${data.width} ${data.height}`} preserveAspectRatio="none" aria-label="Freehand drawing"><polyline points={data.points.map((p:any)=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#187c77" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke"/></svg></div>}

export function JunctionNode(){return <div className="fishbone-junction"><Handle id="in" type="target" position={Position.Left}/><Handle id="out" type="source" position={Position.Right}/></div>}
