import type {Node,Edge} from '@xyflow/react';
export function newId(){return typeof crypto.randomUUID==='function'?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('')}
export const boardMethods=['Fishbone / Ishikawa','Timeline','Process Map','Causal Branching','Events & Causal Factors Chart','Logic Fault Tree','Brainstorming & Affinity Diagram','Ease Benefit Matrix'] as const;
export type Method=typeof boardMethods[number];
export type Board={nodes:Node[];edges:Edge[]};
export const configs:Record<Method,{direction:'LR'|'TB'|'mixed'|'free';step:number;palette:string[];hint:string}>={
'Fishbone / Ishikawa':{direction:'LR',step:4,palette:['Category','Causal factor','Evidence','Note'],hint:'Group possible causes under People, Methods, Machines, Materials, Measurement and Environment. Verify assumptions with evidence.'},
'Timeline':{direction:'LR',step:2,palette:['Event','Note'],hint:'Arrange dated events from left to right. Add an event from the + on a card.'},
'Process Map':{direction:'LR',step:2,palette:['Process step','Decision','Note'],hint:'Map the process from left to right. Decisions can branch downward.'},
'Causal Branching':{direction:'TB',step:4,palette:['Problem','Causal factor','Root cause','Evidence'],hint:'Break the problem into contributing factors. Dashed outlines mark assumptions.'},
'Events & Causal Factors Chart':{direction:'mixed',step:4,palette:['Event','Condition','Causal factor','Root cause','Note'],hint:'Map events horizontally, then trace conditions and factors upward through the lanes.'},
'Logic Fault Tree':{direction:'TB',step:4,palette:['Top event','Event','AND gate','OR gate','Basic event'],hint:'Build downward from the top event. AND requires all inputs; OR requires any input.'},
'Brainstorming & Affinity Diagram':{direction:'free',step:5,palette:['Group','Note'],hint:'Drop a note inside a group to attach it. Drag it out to ungroup. Groups move their notes.'},
'Ease Benefit Matrix':{direction:'free',step:5,palette:['Solution','Note'],hint:'Position solutions by impact and ease. Their quadrant is calculated from their location.'}
};
export const sketches=['Text','Rectangle','Ellipse','Diamond'];
export const edge=(id:string,source:string,target:string,sourceHandle='out',targetHandle='in',label?:string):Edge=>({id,source,target,sourceHandle,targetHandle,type:'smoothstep',label,markerEnd:{type:'arrowclosed' as any},style:{stroke:'#53758b',strokeWidth:1.7}});
export function node(method:Method,id:string,kind:string,label:string,x:number,y:number,extra:Record<string,unknown>={}):Node{
const dir=configs[method].direction;let w=220,h=130;if(kind==='Event'&&method==='Timeline'){w=245;h=150}if(['Problem','Top event'].includes(kind)){w=260;h=170}if(kind.endsWith('gate')){w=105;h=95}if(['Causal factor','Root cause','Basic event'].includes(kind)){h=160}if(kind==='Text'){w=220;h=80}if(kind==='Note'){w=210;h=125}
return {id,type:'method',position:{x,y},style:{width:w,height:h},data:{kind,label,date:'',method,direction:kind==='Evidence'?'LR':dir==='mixed'?(kind==='Event'?'LR':'BT'):dir,status:['Causal factor','Root cause','Basic event'].includes(kind)?'Assumption':'',...extra}};
}
export function frame(id:string,label:string,x:number,y:number,w:number,h:number,tone='blue'):Node{return{id,type:'frame',position:{x,y},style:{width:w,height:h},data:{kind:'Group',label,tone},zIndex:-1}}
export function template(method:Method):Board{
const n=(id:string,k:string,t:string,x:number,y:number,e={})=>node(method,id,k,t,x,y,e);
if(method==='Fishbone / Ishikawa'){
const categories=['People','Methods','Machines','Materials','Measurement','Environment'];
const nodes=[n('effect','Problem','Define the problem',1140,235),...categories.map((label,i)=>n('category-'+i,'Category',label+'\nAdd possible causes…',(i%3)*350,i<3?20:490)),...[0,1,2].map(i=>({id:'spine-'+i,type:'junction',position:{x:255+i*350,y:315},style:{width:2,height:2},data:{kind:'Junction',label:'',direction:'LR',method}}))];
const straight=(id:string,source:string,target:string)=>({...edge(id,source,target),type:'straight',markerEnd:undefined});
return {nodes,edges:[...categories.map((_,i)=>straight('bone-'+i,'category-'+i,'spine-'+(i%3))),straight('spine-a','spine-0','spine-1'),straight('spine-b','spine-1','spine-2'),{...edge('spine-effect','spine-2','effect'),type:'straight'}]};}
if(method==='Timeline')return{nodes:[n('t1','Event','New format introduced',30,120,{date:'02 Aug · 08:00'}),n('t2','Event','First extended changeover',335,120,{date:'05 Aug · 14:30'}),n('t3','Event','QA clearance delay recorded',640,120,{date:'08 Aug · 09:15',highlight:true})],edges:[edge('te1','t1','t2'),edge('te2','t2','t3')]};
if(method==='Process Map')return{nodes:[n('p1','Process step','Stop & clean line',0,100),n('p2','Process step','Change format parts',280,100),n('p3','Decision','QA clearance received?',570,95),n('p4','Process step','Restart production',850,100),n('p5','Process step','Resolve clearance issues',570,350,{highlight:true})],edges:[edge('pe1','p1','p2'),edge('pe2','p2','p3'),edge('pe3','p3','p4','out','in','Yes'),edge('pe4','p3','p5','branch','top','No'),edge('pe5','p5','p3','top-out','branch-in','Recheck')]};
if(method==='Causal Branching')return{nodes:[n('c0','Problem','Changeovers exceed the 60-minute standard',390,20),n('c1','Causal factor','Waiting for QA clearance',100,280),n('c2','Causal factor','Format parts unavailable',680,280),n('c3','Root cause','QA coverage does not match changeover schedule',100,530),n('c4','Evidence','Compare release timestamps with the staffing roster',390,540,{direction:'LR'})],edges:[edge('ce1','c0','c1'),edge('ce2','c0','c2'),edge('ce3','c1','c3'),edge('ce4','c3','c4','right','in','Evidence to collect')]};
if(method==='Logic Fault Tree')return{nodes:[n('f0','Top event','Changeover exceeds target',380,0),n('f1','OR gate','OR',460,235),n('f2','Event','QA clearance is delayed',90,420),n('f3','Event','Set-up is delayed',690,420),n('f4','AND gate','AND',750,620),n('f5','Basic event','Format part is missing',575,800),n('f6','Basic event','No ready spare is available',865,800)],edges:[edge('fe1','f0','f1'),edge('fe2','f1','f2'),edge('fe3','f1','f3'),edge('fe4','f3','f4'),edge('fe5','f4','f5'),edge('fe6','f4','f6')]};
if(method==='Events & Causal Factors Chart'){
const lanes=[frame('system','SYSTEM · Planning, resources & standards',0,0,1100,240),frame('local','LOCAL · Conditions & causal factors',0,270,1100,240,'mint'),frame('events','TIMELINE · Events & actions',0,540,1100,240,'gray')].map(f=>({...f,draggable:false,selectable:false,deletable:false,data:{...f.data,kind:'Lane'}}));
const child=(id:string,k:string,t:string,x:number,y:number,parentId:string)=>({...n(id,k,t,x,y),parentId,extent:'parent' as const});return{nodes:[...lanes,child('e1','Event','Cleaning completed',40,70,'events'),child('e2','Event','Waiting for QA',400,70,'events'),child('e3','Event','Production restarted',800,70,'events'),child('ec1','Condition','QA unavailable at handover',400,70,'local'),child('ec2','Root cause','Coverage planned without changeover demand',400,70,'system')],edges:[edge('ee1','e1','e2'),edge('ee2','e2','e3'),edge('ee3','e2','ec1','top-out','in'),edge('ee4','ec1','ec2')]}}
if(method==='Brainstorming & Affinity Diagram')return{nodes:[frame('g1','QA & communication',0,10,340,450,'mint'),frame('g2','Equipment & parts',400,10,340,450,'blue'),{...n('a1','Note','Notify QA before the line stops',35,90),parentId:'g1'},{...n('a2','Note','Agree on a release handover',35,255),parentId:'g1'},{...n('a3','Note','Prepare format parts before changeover',35,90),parentId:'g2'},n('a4','Note','Unsorted idea — drag into a group',800,100)],edges:[]};
return{nodes:[{id:'matrix',type:'matrix',position:{x:0,y:0},style:{width:1000,height:680},data:{kind:'Matrix',label:'Impact / ease'},draggable:false,selectable:false,deletable:false,zIndex:-1},n('s1','Solution','Prepare format kits',640,150),n('s2','Solution','Redesign the cartoner set-up',135,155),n('s3','Solution','Update the handover checklist',620,465)],edges:[]};
}
export function dimensions(n:Node){return {width:Number(n.measured?.width||n.width||n.style?.width||220),height:Number(n.measured?.height||n.height||n.style?.height||130)}}
export function absolute(n:Node,nodes:Node[]):{x:number;y:number}{const parent=nodes.find(p=>p.id===n.parentId);return parent?{x:n.position.x+parent.position.x,y:n.position.y+parent.position.y}:n.position}
export function quadrant(n:Node,nodes:Node[]){const m=nodes.find(n=>n.type==='matrix');if(!m)return'';const p=absolute(n,nodes),x=p.x+dimensions(n).width/2-m.position.x,y=p.y+dimensions(n).height/2-m.position.y;if(x<70||x>950||y<70||y>610)return'Outside matrix';return y<340?(x>=510?'Highest priority · high impact / easy':'Evaluate further · high impact / difficult'):(x>=510?'Evaluate further · low impact / easy':'Lowest priority · low impact / difficult')}
export function readBoard(board:Board,method:Method){return{method,nodes:board.nodes.map(n=>({id:n.id,kind:n.data.kind,label:n.data.label,date:n.data.date,status:n.data.status,group:n.parentId,position:absolute(n,board.nodes),...dimensions(n),...(n.data.kind==='Solution'?{quadrant:quadrant(n,board.nodes)}:{}),...(n.type==='freehand'?{points:n.data.points}:{} )})),edges:board.edges.map(e=>({from:e.source,to:e.target,label:e.label,fromPort:e.sourceHandle,toPort:e.targetHandle}))}}
export function validConnection(board:Board,method:Method,source:string,target:string){if(source===target)return false;const ns=board.nodes;if(!ns.some(n=>n.id===source)||!ns.some(n=>n.id===target))return false;if(!['Causal Branching','Logic Fault Tree'].includes(method))return true;
const seen=new Set<string>();const visit=(id:string):boolean=>{if(id===source)return true;if(seen.has(id))return false;seen.add(id);return board.edges.filter(e=>e.source===id).some(e=>visit(e.target))};return !visit(target)}
export function issues(board:Board,method:Method){const notes:string[]=[];if(method==='Logic Fault Tree'){for(const n of board.nodes.filter(n=>String(n.data.kind).endsWith('gate'))){if(board.edges.filter(e=>e.source===n.id).length<2)notes.push(`${n.data.kind} needs at least two input events below it.`)}notes.push('Qualitative fault tree: event probabilities are not calculated.')}if(method==='Ease Benefit Matrix'&&board.nodes.some(n=>n.data.kind==='Solution'&&quadrant(n,board.nodes)==='Outside matrix'))notes.push('A solution is outside the matrix; move it inside to assign a quadrant.');return notes}
export type Proposal={message:string;nodes:{id:string;kind:string;label:string;date?:string;status?:string;x:number;y:number;parentId?:string}[];edges:{source:string;target:string;label?:string}[]};
export function applyProposal(board:Board,method:Method,p:Proposal):Board{const ids=new Map<string,string>();const added:Node[]=[];const allowed=[...configs[method].palette,...sketches];const existing=new Set(board.nodes.map(n=>n.id));if(p.nodes.length>30||p.edges.length>45||board.nodes.length+p.nodes.length>200||board.edges.length+p.edges.length>400)throw new Error('The proposal is too large. Ask for a smaller addition.');
for(const n of p.nodes){if(!allowed.includes(n.kind)||ids.has(n.id)||existing.has(n.id))throw new Error('The proposal contains unsupported or duplicate elements.');if(!Number.isFinite(n.x)||!Number.isFinite(n.y)||Math.abs(n.x)>15000||Math.abs(n.y)>15000)throw new Error('An element position is invalid.');ids.set(n.id,newId());}
for(const n of p.nodes){const id=ids.get(n.id)!;let v=n.kind==='Group'?frame(id,n.label,n.x,n.y,340,440):node(method,id,n.kind,n.label,n.x,n.y,{date:n.date||'',status:['Causal factor','Root cause','Basic event'].includes(n.kind)?'Assumption':''});if(n.parentId){const parentId=ids.get(n.parentId)||n.parentId;const parent=[...board.nodes,...added].find(x=>x.id===parentId);if(v.type==='frame'||!parent||!['frame'].includes(parent.type||''))throw new Error('The proposed group or lane is unavailable.');v={...v,parentId,...(parent.data.kind==='Lane'?{extent:'parent' as const}:{})}}added.push(v)}
let result={nodes:[...board.nodes,...added],edges:[...board.edges]};for(const e of p.edges){const source=ids.get(e.source)||e.source,target=ids.get(e.target)||e.target;if(!validConnection(result,method,source,target))throw new Error('The proposal contains an invalid connection or cycle.');const sourceNode=result.nodes.find(n=>n.id===source)!;const targetNode=result.nodes.find(n=>n.id===target)!;if(['frame','matrix','freehand'].includes(sourceNode.type||'')||['frame','matrix','freehand'].includes(targetNode.type||'')||sourceNode.data.direction==='free'||targetNode.data.direction==='free')throw new Error('These elements do not support connections.');const upward=method==='Events & Causal Factors Chart'&&sourceNode.data.kind==='Event'&&targetNode.data.kind!=='Event';result.edges.push(edge(newId(),source,target,upward?'top-out':'out','in',e.label))}return expandLanes(result,method)}

export function expandLanes(board:Board,method:Method):Board {
if(method!=='Events & Causal Factors Chart')return board;
const width=Math.max(1100,...board.nodes.filter(n=>n.parentId).map(n=>n.position.x+dimensions(n).width+40));
return {...board,nodes:board.nodes.map(n=>n.data.kind==='Lane'?{...n,style:{...n.style,width}}:n)}
}
